# Generated by Django 3.0.4 on 2020-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='front.Tag', verbose_name='标签集'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
    ]
